### ISSUE TITLE
ENOENT, no such file or directory  .tmp/0/bower_components/FakeXMLHttpRequest/fake_xml_http_request.js

### ISSUE THREAD

**Issue by Iftahh** [elwayman02/ember-cli-opinionated#28]
Starting a fresh new project, I installed the ember-cli-opinionated using the latest master branch of this repo and then I get build error of missing file:

To recreate:

```
> ember init
...
> ember install https://github.com/elwayman02/ember-cli-opinionated
... (answered Y to all questions)
> ember build    (and of course same error for ember serve, ember test, etc...)
version: 1.13.8
Build failed.
Error: ENOENT, no such file or directory '...../tmp/concat_with_maps-input_base_path-HCN9tWgD.tmp/0/bower_components/FakeXMLHttpRequest/fake_xml_http_request.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at ConcatWithMaps.keyForFile (/Users/iftah/devel/b4p/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/iftah/devel/b4p/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/iftah/devel/b4p/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/iftah/devel/b4p/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/iftah/devel/b4p/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/iftah/devel/b4p/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/iftah/devel/b4p/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by elwayman02** [comment]
@Iftahh did you upgrade to ember-cli master branch before installing ember-cli-opinionated? See [this note](https://github.com/elwayman02/ember-cli-opinionated#installation) for more information. When addons are installed via Ember-CLI 1.13.8, it's a common problem that some of their blueprints did not run successfully. I would guess that you are missing some dependencies that were supposed to be installed. You could fix this by upgrading to Ember-CLI master and running `ember install ember-cli-opinionated`, or you could manually trigger the blueprints for each addon installed by this package (ie `ember g ember-cli-mirage`).

**Comment by Iftahh** [comment]
err, oops sorry, @elwayman02  you are right.  I skipped an 'npm link' and used the older, global installed ember-cli.
Using the master ember-cli I get everything installed fine (except 'already installed' warnings...) and building just fine  (well, except the deprecations and suave warnings...)

Thanks for a awesome bootstraping!  
I love it!
